modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="streamertrails"
version="1.0"
displayName="Streamer Visual Trails"
description='''
Leaves glowing particle trail behind the player.
'''

[[dependencies.streamertrails]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.streamertrails]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="CLIENT"
